from PIL import Image
import numpy as np
import cv2
import functools
import boto3

from dotenv import load_dotenv
import os

load_dotenv()

rekognition = None

# `HOMOGLYPHS` generated by Gemini 3.1 Pro (on 6/4/2026)
HOMOGLYPHS = {
    ord('В'): 'B', ord('в'): 'B', ord('С'): 'C', ord('с'):'C', ord('А'): 'A', ord('Е'): 'E',
    ord('О'): 'O', ord('Р'): 'P', ord('Т'): 'T', ord('Х'): 'X',
    ord('М'): 'M', ord('Н'): 'H', ord('Β'): 'B', ord('Ο'): 'O' # Includes Cyrillic and Greek
}

if "norekognition" in os.environ and os.environ["norekognition"] == 'true':
	import pytesseract
	print("No rekognition!")
else:
	os.environ["norekognition"] = 'false'
	# https://docs.aws.amazon.com/boto3/latest/reference/services/rekognition.html
	rekognition = boto3.client('rekognition')

if "dev" not in os.environ:
	os.environ["dev"] = 'false'

# (`height`,`width`)
GRID_SIZE = (4,4)
TOTAL_LETTERS = GRID_SIZE[0]*GRID_SIZE[1]

def processImage(img:Image.Image):
	img = img.resize((1170,2532))
	im = cv2.cvtColor(np.array(img),cv2.COLOR_RGB2BGR)

	grid = extract_grid(im)
	print(*grid,sep="\n")
	return grid

def extract_grid(im:cv2.typing.MatLike):
	threshed = cv2.extractChannel(im,2)
	threshed = cv2.convertScaleAbs(threshed,alpha=10)
	ret, threshed = cv2.threshold(threshed,127,255,cv2.THRESH_BINARY)
	contours, hierarchy = cv2.findContours(threshed,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
	out=cv2.cvtColor(threshed,cv2.COLOR_GRAY2BGR)

	HEIGHT, WIDTH = threshed.shape[0], threshed.shape[1]

	def good_pos_and_size(rect):
		x,y,w,h = rect

		if w > 0.2*WIDTH or h > 0.2*HEIGHT: return False # i.e. too big
		if y < 0.3*HEIGHT: return False # i.e. too high
		if x+w > WIDTH or y+h > HEIGHT: return False # i.e. out of bounds
		return True
	
	def remove_overlap(rects:list[tuple[int,int,int,int]]):
		bad = set()
		for i in range(len(rects)):
			for j in range(i+1,len(rects)):
				overlap = cv2.rectangleIntersectionArea(rects[i],rects[j])
				if overlap > 0.5 * min(rects[i][2]*rects[i][3],rects[j][2]*rects[j][3]):
					# choose min area one and kill it
					if rects[i][2]*rects[i][3] >= rects[j][2]*rects[j][3]: bad.add(j)
					else: bad.add(i)
		out = []
		for i in range(len(rects)):
			if i not in bad: out.append(rects[i])
		
		return out
	area = lambda rect: abs(rect[2]*rect[3])
	cmp_area = lambda a,b: area(b)-area(a) # descending area-wise
	
	rects = list(map(cv2.boundingRect,contours))
	rects = filter(good_pos_and_size, rects)
	rects = remove_overlap(list(rects))
	rects = sorted(rects, key=functools.cmp_to_key(cmp_area))

	if len(rects) < TOTAL_LETTERS:
		print("WHAT?!?")
		raise IndexError(f"Not enough letters detected; Detected {len(rects)}, board should have atleast {TOTAL_LETTERS}")
	
	rects = rects[:16]
	
	letterLocs = []
	
	tt=HEIGHT
	tb=0
	tl=WIDTH
	tr=0
	
	for rect in rects:
		x,y,w,h = rect
		top, bottom = max(y-20,0), min(y+h+20,HEIGHT)
		left, right = max(x-20,0), min(x+w+20,WIDTH)

		tl = min(tl,left)
		tr = max(tr,right)
		tt = min(tt,top)
		tb = max(tb,bottom)

		if os.environ["norekognition"] == 'true':
			letter = ""
			text = str(pytesseract.image_to_string(threshed[top:bottom,left:right],lang="eng",config=r'--oem 3 --psm 6'))

			if len(text) != 0:
				letter = text[0].upper()
			else: letter = "I" # bc I is the only one tesseract doesnt like

			if os.environ["dev"] == 'true':
				cv2.rectangle(out,(left,top),(right,bottom),(0,255,0),2) # DEBUG: outline detected characters' aabbs
				cv2.putText(out,letter,(x,y+10),cv2.FONT_HERSHEY_SIMPLEX,2,(0,0,255),2) # DEBUG: superimpose detected characters
			letterLocs.append(((y,x),letter))
	
	if os.environ["norekognition"] == 'false':
		# print("------------")
		success, encoded = cv2.imencode('.png',threshed[tt:tb,tl:tr])
		if not success:
			raise RuntimeError("Failed to encode image")
		
		# https://docs.aws.amazon.com/boto3/latest/reference/services/rekognition/client/detect_text.html#
		detections:list[dict] = rekognition.detect_text(
			Image={ 'Bytes': encoded.tobytes(), },
		)["TextDetections"]
		
		for chunk in detections:
			text = str(chunk['DetectedText']).replace(" ","")
			text = text.translate(HOMOGLYPHS).upper()
			aabb = chunk['Geometry']['BoundingBox']
			x1, w1 = map(lambda a: int(a*abs(tr-tl)),(aabb['Left'],aabb['Width']))
			y1, h1 = map(lambda a: int(a*abs(tb-tt)),(aabb['Top'],aabb['Height']))
			x1+=tl
			y1+=tt
			x, y, w, h = aabb['Left'], aabb['Top'], aabb['Width'], aabb['Height']
			top, bottom = max(y1,0), min(y1+h1,HEIGHT)
			left, right = max(x1,0), min(x1+w1,WIDTH)

			if w>0.2: continue

			if os.environ["dev"] == 'true':
				cv2.rectangle(out,(left,top),(right,bottom),(0,255,0),2) # DEBUG: outline detected characters' aabbs
				cv2.putText(out,text,(x1,y1+10),cv2.FONT_HERSHEY_SIMPLEX,2,(0,0,255),2) # DEBUG: superimpose detected characters
			
			c=text[0]
			cx = x+w/2
			cy = y+h/2
			letterLocs.append(((cy,cx),c))

	letterLocs = removeLocDuplicates(letterLocs)
	letterLocs.sort() # sorts from **top to bottom**
	annotatedGrid = [
		sorted(
			letterLocs[i*GRID_SIZE[1]:(i+1)*GRID_SIZE[1]],
			key=functools.cmp_to_key(lambda a,b: a[0][1]-b[0][1])
			) for i in range(GRID_SIZE[0])
	]
	if (os.environ["dev"] == 'true'):
		Image.fromarray(cv2.cvtColor(out,cv2.COLOR_BGR2RGB)).save("test/img.png") # DEBUG: output image
		cv2.imshow("hallo",out)
		cv2.waitKey(100000)
	grid = list(map(lambda a: "".join(map(lambda b: b[1],a)),annotatedGrid))

	return grid

def removeLocDuplicates(letterLocs:list[tuple[tuple[float,float],str]]) -> list[tuple[tuple[float,float],str]]:
	i=0
	while i < len(letterLocs):
		for j in range(len(letterLocs)-1,i+1,-1):
			if abs(letterLocs[i][0][0] - letterLocs[j][0][0]) + abs(letterLocs[i][0][1] - letterLocs[j][0][1]) < 0.1:
				letterLocs.pop(j)
		i+=1
	return letterLocs

if __name__ == "__main__" and os.environ["dev"] == 'true':
	i=8
	img = Image.open(f"test/{i}.png").resize((195,422))
	processImage(img)
	print("hooray!")