#!/bin/bash
rm -rf package
mkdir package
# uv pip freeze > package/requirements.txt
cp requirements-build.txt package/requirements.txt
cp *.py package
cp -R wordslists package

# create the lambda python container, install tesseract and dependencies,
# then copy the tesseract binary, tessdata and required shared libs into package
# **This command and only this one written by claude :) **
docker run --rm --platform linux/arm64 -v "$PWD":/var/task --entrypoint bash public.ecr.aws/lambda/python:3.14 -c "\
	python -m pip install -r package/requirements.txt -t package \
"

rm -f deployment_package*.zip
cd package
zip -r ../deployment_package.zip .
cd ..
aws s3 cp ./deployment_package.zip s3://wordhuntercode/
echo "Uploaded to s3!"

rm -rf package &
aws lambda update-function-code --function-name wordhunter --s3-bucket wordhuntercode --s3-key deployment_package.zip --no-cli-pager &
wait;
sleep 0.25;
rm -rf package # bro `package` is so persistent idk what to do about it 😭